
variables:
  HELM_DOCKER_TAG: "v2.14.0"
  GSG_DOCKER_TAG: "v0.21.0"
  DEFAULT_DOCKER_TAG: "3.9.3"

  OPEN_API_DOCKER_VERSION: "v4.0.1"
  GSG_TAG_PREFIX: "releases/"


stages:
  - MergeRequest
  - BuildNumber
  - Build
  - Lint
  - Docker
  - Deploy
  - TagBuildNumber
  - TagVersion


##############
# Merge jobs #
##############

.build_mr_template:
  stage: MergeRequest
  only:
    - merge_requests


.lint_mr_template:
  stage: MergeRequest
  only:
    - merge_requests


LintHelmMR:
  stage: MergeRequest
  image: devth/helm
  only:
    - merge_requests
  script:
    - helm lint chart -f chart.yml


.test_mr_template:
  stage: MergeRequest
  only:
    - merge_requests
  script:
    - echo 'Tests ✅'


###############
# Master jobs #
###############

BuildNumber:
  stage: BuildNumber
  image: samueldebruyn/debian-git
  environment:
    name: development
  only:
    - master
  script:
    - git rev-list --count origin/master > .build_number
    - echo "Build number:"$(cat .build_number)
  artifacts:
    paths:
      - .build_number


TagBuildNumber:
  stage: TagBuildNumber
  image: samueldebruyn/debian-git
  environment:
    name: development
  only:
    - master
  script:
    - BUILD_NUMBER=`cat .build_number`
    - echo "Build number $BUILD_NUMBER"

    - git tag builds/$BUILD_NUMBER
    - git remote set-url origin https://gitlab-ci-token:$GL_TOKEN@gitlab.com/$CI_PROJECT_PATH.git/
    - git push origin builds/$BUILD_NUMBER


TagVersion:
  stage: TagVersion
  image: registry.gitlab.com/juhani/go-semrel-gitlab:$GSG_DOCKER_TAG
  environment:
    name: development
  when: manual
  only:
    - master
  script:
    - release next-version
    - release tag


##################
# Build tag jobs #
##################

VersionDev:
  stage: BuildNumber
  image: alpine:$DEFAULT_DOCKER_TAG
  environment:
    name: development
  only:
    - /builds/
  except:
    - branches
  script:
    - echo $CI_COMMIT_TAG | sed -n 's/builds\/\([0-9]+\)/\1/p' > .build_number
    - echo "Build number "$(cat .build_number)
  artifacts:
    paths:
      #TODO maybe this should be a different name? 🤔
      - .build_number


.build_dev_template:
  extends: .build_template
  environment:
    name: development
  variables:
    ENV: dev
  only:
    - /builds/
  except:
    - branches


BuildAndUploadDockerDev:
  extends: .build_and_upload_docker_template
  environment:
    name: development
  only:
    - /builds/
  except:
    - branches
  variables:
    REGISTRY_PATH: builds


DeployChartDev:
  extends: .deploy_chart_template
  environment:
    name: development
  variables:
    PROJECT: $PROJECT_DEV
    REGISTRY_PATH: builds
    API_ENDPOINT: $API_ENDPOINT_DEV
    KUBERNETES_SA: KUBERNETES_SA_DEV
  only:
    - /builds/


DocumentationDev:
  extends: .documentation_template
  environment:
    name: development
  only:
    - /builds/
  dependencies:
    - VersionDev


DeployDocumentationDev:
  extends: .deploy_documentation_template
  environment:
    name: development
  variables:
    PROJECT: $PROJECT_DEV
  only:
    - /builds/
  dependencies:
    - VersionDev
    - DocumentationDev


#####################
# Releases tag jobs #
#####################

BuildNumberProd:
  stage: BuildNumber
  image: alpine:$DEFAULT_DOCKER_TAG
  environment:
    name: production
  only:
    - /releases/
  except:
    - branches
  script:
    - echo $CI_COMMIT_TAG | sed -n 's/releases\/\([0-9]+.[0-9]+.[0-9]+\)/\1/p' > .build_number
    - cat .build_number
  artifacts:
    paths:
      - .build_number


.build_prod_template:
  extends: .build_template
  environment:
    name: production
  variables:
    ENV: prod
  only:
    - /releases/
  except:
    - branches


BuildAndUploadDockerProd:
  extends: .build_and_upload_docker_template
  environment:
    name: production
  only:
    - /releases/
  except:
    - branches
  variables:
    REGISTRY_PATH: releases


DeployChartProd:
  extends: .deploy_chart_template
  environment:
    name: production
  variables:
    PROJECT: $PROJECT_PROD
    REGISTRY_PATH: releases
    API_ENDPOINT: $API_ENDPOINT_PROD
    KUBERNETES_SA: KUBERNETES_SA_PROD
  only:
    - /releases/


DocumentationProd:
  extends: .documentation_template
  environment:
    name: production
  only:
    - /releases/
  dependencies:
    - BuildNumberProd


DeployDocumentationProd:
  extends: .deploy_documentation_template
  environment:
    name: production
  variables:
    PROJECT: $PROJECT_PROD
  only:
    - /releases/
  dependencies:
    - BuildNumberProd
    - DocumentationProd


#############
# Templates #
#############

.build_template:
  stage: Build


.deploy_chart_template:
  stage: Deploy
  image: devth/helm:$HELM_DOCKER_TAG
  except:
    - branches
  script:
    - BUILD_NUMBER=`cat .build_number`
    - echo "Build number $BUILD_NUMBER"
    - KUBERNETES_SA=`eval echo "$"$KUBERNETES_SA`

    - gcloud auth activate-service-account --key-file=$KUBERNETES_SA --project $PROJECT
    - gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT

    - helm init --client-only

    - helm upgrade $NAME chart
      --install
      --values chart.yml
      --version $BUILD_NUMBER
      --set image.repository=$CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH
      --set image.tag=$BUILD_NUMBER
      --set ingress.host=$API_ENDPOINT


.documentation_template:
  stage: Build
  image: openapitools/openapi-generator-cli:$OPEN_API_DOCKER_VERSION
  except:
    - branches
  script:
    - BUILD_NUMBER=`cat .build_number`
    - echo "Build number $BUILD_NUMBER"

    - sed -i.bak 's/BUILD_NUMBER/'$build_number'/' swagger.yml # TODO maybe find a better way to do this
    - java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g html2 -i swagger.yml -o documentation
  artifacts:
    paths:
      - documentation


.deploy_documentation_template:
  stage: Deploy
  image: google/cloud-sdk:alpine
  except:
    - branches
  script:
    - BUILD_NUMBER=`cat .build_number`
    - echo "Build number $BUILD_NUMBER"

    - gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_ACCOUNT_WS_DOC_BUCKET --project=$PROJECT
    #TODO is the bucket name correct? find a better name?
    - gsutil cp -r documentation gs://$BUCKET_DOCUMENTION/$NAME/$BUILD_NUMBER


.build_and_upload_docker_template:
  stage: Docker
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    # TODO update this when this is resolved https://gitlab.com/gitlab-org/gitlab-runner/issues/4566
    # Solution from https://gitlab.com/gitlab-org/gitlab-runner/issues/4566#note_199261985
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - BUILD_NUMBER=`cat .build_number`
    - echo "Build number $BUILD_NUMBER"

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER

